# Generated by Django 3.0 on 2021-07-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogotypeOfProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='logo.jpg', upload_to='avatars/')),
            ],
            options={
                'verbose_name': 'Logo of project',
            },
        ),
    ]
