# Generated by Django 3.0 on 2021-07-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_logotypeofproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogotypeOfProject',
        ),
    ]
